<?xml version="1.0"?>
<package format="3">
  <name>wearnav_recorder</name>
  <version>0.1.0</version>
  <description>Session control and rosbag recording for WearNav.</description>
  <maintainer email="lisec@todo.todo">lisec</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>wearnav_interfaces</depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>ros2bag</exec_depend>
  <exec_depend>rosbag2_transport</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
